name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'Virtual-Farm-Market-main/client/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Build
        working-directory: ./Virtual-Farm-Market-main/client/Virtual-Farm-Market
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync S3
        working-directory: ./Virtual-Farm-Market-main/client/Virtual-Farm-Market
        run: |
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Clear Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
