name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'Virtual-Farm-Market-main/server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO: vfm-backend
        run: |
          docker build -t $REGISTRY/$REPO:latest ./Virtual-Farm-Market-main/server
          docker push $REGISTRY/$REPO:latest
